# Even fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
	# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def infinite_fibonacci():
	"""A generator that generates fibonacci numbers infinitely"""
	a = b = 1  #initializing first variables.
	while True:
		yield a
		a, b = b, a + b 


def even_fibonacci(limit):
	"""A function to find the even fibonacci up
	to a given limit"""
	accum = 0
	for x in infinite_fibonacci():
		if x > limit:
			break
		if x % 2 == 0:
			accum += x
	return accum


if __name__ == '__main__':
	print(even_fibonacci(4000000))


