# Even fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
	# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

from typing import Generator


def infinite_fibonacci() -> Generator[int, None, None]:
	"""A generator that generates fibonacci numbers infinitely."""
	a = b = 1  #initializing first variables.
	while True:
		yield a	
		# add the next number to the first
		# and initialize the second, then
		# put it in the first and yield it.							
		a, b = b, a + b 				


def even_fibonacci(limit: int) -> int:
	"""A function to find the even fibonacci up
	to a given limit.
	
	:limit -> The upper boundary"""
	accum = 0
	for x in infinite_fibonacci():				# loop through the fibonacci generator
		if x > limit:
			return accum						# limit reached, exit loop
		if x % 2 == 0:							# check if fibonacci number is even.
			accum += x
	


if __name__ == '__main__':
	print(even_fibonacci(4000000))


